package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"strings"

	"github.com/TaiwoDevOps/todo-graphql/errors"
	"github.com/TaiwoDevOps/todo-graphql/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {

	if len(strings.TrimSpace(input.Text)) == 0 {
		return nil, &errors.ValidationError{
			Field: "text",
			Msg:   "text cannot be empty",
		}
	}

	if len(input.Text) > 255 {
		return nil, &errors.ValidationError{
			Field: "text",
			Msg:   "text cannot be longer than 255 characters",
		}
	}

	createdTodo := r.TodoStrore.CreateTodo(input.Text)

	if createdTodo == nil {
		return nil, &errors.DuplicateError{
			Resource: "Todo",
			Field:    "text",
			Value:    input.Text,
		}
	}

	return &model.Todo{
		ID:        createdTodo.ID,
		Text:      createdTodo.Text,
		Done:      createdTodo.Done,
		CreatedAt: createdTodo.CreatedAt,
		UpdatedAt: createdTodo.UpdatedAt,
	}, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodo) (*model.Todo, error) {

	if len(strings.TrimSpace(*input.Text)) == 0 {
		return nil, &errors.ValidationError{
			Field: "text",
			Msg:   "text cannot be empty",
		}
	}

	if len(*input.Text) > 255 {
		return nil, &errors.ValidationError{
			Field: "text",
			Msg:   "text cannot be longer than 255 characters",
		}
	}
	updatedTodo, err := r.TodoStrore.UpdateTodo(id, input.Text, input.Done)
	if err != nil {
		return nil, err
	}

	return &model.Todo{
		ID:        updatedTodo.ID,
		Text:      updatedTodo.Text,
		Done:      updatedTodo.Done,
		CreatedAt: updatedTodo.CreatedAt,
		UpdatedAt: updatedTodo.UpdatedAt,
	}, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	status := r.TodoStrore.DeleteTodo(id)

	if !status {
		return false, &errors.NotFoundError{
			Resource: "Todo",
			ID:       id,
		}
	}

	return true, nil
}

// ToggleTodo is the resolver for the toggleTodo field.
func (r *mutationResolver) ToggleTodo(ctx context.Context, id string) (*model.Todo, error) {
	toggledTodo := r.TodoStrore.ToggleTodo(id)

	if toggledTodo == nil {
		return nil, &errors.NotFoundError{
			Resource: "Todo",
			ID:       id,
		}
	}

	return &model.Todo{
		ID:        toggledTodo.ID,
		Text:      toggledTodo.Text,
		Done:      toggledTodo.Done,
		CreatedAt: toggledTodo.CreatedAt,
		UpdatedAt: toggledTodo.UpdatedAt,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todos := r.TodoStrore.GetAll()

	result := make([]*model.Todo, len(todos))

	for i, todo := range todos {
		result[i] = &model.Todo{
			ID:        todo.ID,
			Text:      todo.Text,
			Done:      todo.Done,
			CreatedAt: todo.CreatedAt,
			UpdatedAt: todo.UpdatedAt,
		}
	}

	return result, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	todo := r.TodoStrore.GetByID(id)

	if todo == nil {
		return nil, &errors.NotFoundError{
			Resource: "Todo",
			ID:       id,
		}
	}

	return &model.Todo{
		ID:        todo.ID,
		Text:      todo.Text,
		Done:      todo.Done,
		CreatedAt: todo.CreatedAt,
		UpdatedAt: todo.UpdatedAt,
	}, nil
}

// TodoByStatus is the resolver for the todoByStatus field.
func (r *queryResolver) TodoByStatus(ctx context.Context, done bool) ([]*model.Todo, error) {
	todos := r.TodoStrore.GetByStatus(done)

	result := make([]*model.Todo, len(todos))

	for i, todo := range todos {
		result[i] = &model.Todo{
			ID:        todo.ID,
			Text:      todo.Text,
			Done:      todo.Done,
			CreatedAt: todo.CreatedAt,
			UpdatedAt: todo.UpdatedAt,
		}
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
